set -u

ABSOLUTE_PATH=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/`basename "${BASH_SOURCE[0]}"`
DOCKER_TOOLS_PATH="$( readlink -f ${ABSOLUTE_PATH%/*} )"
DOCKER_BASE_PATH="${DOCKER_TOOLS_PATH%/*}"
DOCKER_BIN_PATH="${DOCKER_BASE_PATH}/bin"
DOCKER_IMAGES_PATH="${DOCKER_BASE_PATH}/images"
DOCKER_MOUNTPOINTS_PATH="${DOCKER_BASE_PATH}/mount_points"
