FROM debian_base:latest

RUN DEBIAN_FRONTEND=noninteractive apt-get install -o Dpkg::Options::='--force-confold'  -y -q --assume-yes  --force-yes iptables iptables-persistent iptables-converter lsof tcpdump ngrep netcat net-tools sysstat ifstat nmon vim


